version: "3.8"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
